#include "compile__compilation_result.c"
#include "compile__memcpy.c"

#include "compile__cpy_print.c"
#include "compile__cpy_one.c"
#include "compile__cpy_for.c"
#include "compile__cpy_def.c"
#include "compile__cpy_if.c"
#include "compile__cpy_return.c"
#include "compile__cpy_last_for.c"