#include "compileAppend__cpy_print.c"
#include "compileAppend__cpy_for.c"
#include "compileAppend__cpy_def.c"
#include "compileAppend__cpy_if.c"
#include "compileAppend__cpy_return.c"
#include "compileAppend__cpy_last_for.c"