from _typeshed import Incomplete

class Template:
    name: Incomplete
    def __init__(self, name: str) -> None: ...
    @property
    def text(self) -> bytes: ...
    def register(self, text: str) -> None: ...
    def unregister(self) -> None: ...
    def __call__(self, parameters: dict = ..., detect_recursion: bool = ...) -> bytes: ...
